# Generated by Django 2.1.7 on 2019-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190326_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='gallery_pics'),
        ),
    ]
