# Generated by Django 2.1.7 on 2019-03-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190326_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
