# Generated by Django 2.1.7 on 2019-03-26 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
    ]
